### ISSUE TITLE
make cross_build faild on centos

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1068]
**What happened**:
when i make cross build edgecore on centos env. it faild:

```
# make cross_build
export GOARCH=arm \
        export GOOS="linux" \
        export GOARM=6 \
        export CGO_ENABLED=1 \
        export CC=arm-linux-gnueabi-gcc; \
        go build cmd/edgecore/edgecore.go
# runtime/cgo
exec: "arm-linux-gnueabi-gcc": executable file not found in $PATH
make: *** [cross_build] Error 2

```

`arm-linux-gnueabi-gcc` only works on ubuntu.  

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release): 
```
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"
```

- Kernel (e.g. `uname -a`):
- Others:

**Comment by kadisi** [comment]
cc @fisherxu @subpathdev @sids-b @kevin-wangzefeng

**Comment by kadisi** [comment]
@subpathdev , after i install arm-gcc in centos, and change CC option from `arm-linux-gnueabi-gcc` to `arm-linux-gnu-gcc`, it still output other error:
```
# yum install gcc-arm-linux-gnu -y
# make cross_build
export GOARCH=arm \
        export GOOS="linux" \
        export GOARM=6 \
        export CGO_ENABLED=1 \
        export CC=arm-linux-gnu-gcc ;\
        go build cmd/edgecore/edgecore.go
# runtime/cgo
_cgo_export.c:3:20: fatal error: stdlib.h: No such file or directory
 #include <stdlib.h>
                    ^
compilation terminated.
make: *** [cross_build] Error 2


```

**Comment by subpathdev** [comment]
I didn't have a good solution to this. (I can say: this happens because the libraries are missing, which are can be used by the correct architecture.) 

My solution is: you could download the tar.gz + the dependencies, which are used by Ubuntu or Debian to cross compile. And place the files in the correct paths on your system. 

As you can see, my problem is my missing knowledge about centos / fedora. @congfairy could you help?

**Comment by VipinKrizz** [comment]
Anybody is still facing this problem?
Because i am also facing this error, While builing the binary of keadm.go in RaspberryPi i get this error message saying
 **#runtime/cgo
exec: "arm-linux-gnueabi-gcc" : executable file not found in $PATH
make: *** [Makefile:6: edgecore] Error 2**
I'm stuck here at this point while installing kubeedge on both laptop(Ubuntu 18.04LTS) and on RaspberryPi 3b(both UbuntuMate and Raspbian Buster Lite)

**Comment by sids-b** [comment]
@VipinKrizz , you need to install gcc on your node. It is a pre requisite for running sqlite

**Comment by VipinKrizz** [comment]
> @VipinKrizz , you need to install gcc on your node. It is a pre requisite for running sqlite

@sids-b 
Is sqlite required for installing kubeedge ?
And i have already installed gcc installed on my laptop as well as my Raspberrypi.
In raspberry pi i have also installed **gcc-arm-linux-gnueabi** 
Still facing the issue.

**Comment by bluefriday** [comment]
@kadisi 
Are there any improvements for this issue?
I am currently stuck on this issue.
