### ISSUE TITLE
use kubelet instead of edged to manage containers

### ISSUE THREAD

**Issue by kadisi** [kubeedge/kubeedge#1083]
**What would you like to be added/modified**:

**Why is this needed**:

currently,  kubeedge use edged module to manage containers on it`s node.  but we need to spend too much effort to enable edged to implement kubelet functionality（such as CRI, CNI, CSI, loadbalance)。  This will lead us to follow the changes in the community  in the future.  And it will also give users a sense of distrust, users are more willing to believe in k8s itself。 

so i suggest delete `edged` modules and use kubelet.

we need modify `MetaManager ` module , and let it disguised as apiserver。  `MetaManager`  provides most of the features of apiserver and serving kubelet.

**Comment by kadisi** [comment]
cc @kevin-wangzefeng @sids-b @fisherxu @rohitsardesai83 @subpathdev @CindyXing

**Comment by rohitsardesai83** [comment]
Can we consider if k3s kubelet can be used ? Resource constraints also needs to be considered.

**Comment by subpathdev** [comment]
I think this is a good idea. Let's target this after the current release and we should consider how much the size of the edge binary will change.

**Comment by kadisi** [comment]
> Can we consider if k3s kubelet can be used ? Resource constraints also needs to be considered.

@rohitsardesai83 that is a good idea, We can advise users to use k3s in kubeedge docs, but it depend on the user's decision.  And I personally feel that resource restrictions are no longer a problem in the near future. We should focus on cloud-side collaboration and edge-side self-management.

**Comment by kadisi** [comment]
@subpathdev  thanks

**Comment by jwzl** [comment]
I agree @rohitsardesai83   @subpathdev   Resource constraints also needs to be considered, in ARM side  especially.

**Comment by sids-b** [comment]
Kubelet opens multiple connections directly with k8s apiserver for receiving resource updates. Hence in office scenarios the reliability of messages cannot be guaranteed. So we created the cloudhub-edgehub so we can apply reliable message delivery on the connection between cloud and edge. 

One thing we can do is separate out the edged and kubelet code so that kubelet can be ventured and easily upgraded. I remember @edisonxiang suggesting an approach of changing meta-client to support watch like functionality and it will move a lot of edged code to vendor.

@edisonxiang can you please share your thoughts on this ?

**Comment by kadisi** [comment]
@sids-b  we indeed use cloudhub-edgehub,  if we use kubelet, We just need to maintain reliable data transfer  cloud and edge.  when edgehub received data, it can passed to `metaManager` module. and we let  `metaManager` provides most of usefull features of apiserver and serving kubelet.

and by the way, we can replace sqlit with boltdb， Boltdb is a key value database, lighter than sql, and simpler syntax.  [etcd](https://github.com/etcd-io/etcd) and [containerd](https://github.com/containerd/containerd) also use it.

**Comment by kadisi** [comment]
> I agree @rohitsardesai83 @subpathdev Resource constraints also needs to be considered, in ARM side especially.

@jwzl , i run native kubelet in my linux node, this is it`s proc status

```
cat /proc/8505/status
Name:	kubelet
Umask:	0022
State:	S (sleeping)
Tgid:	8505
Ngid:	0
Pid:	8505
PPid:	1
TracerPid:	0
Uid:	0	0	0	0
Gid:	0	0	0	0
FDSize:	128
Groups:
VmPeak:	 1532472 kB
VmSize:	 1532468 kB
VmLck:	       0 kB
VmPin:	       0 kB
VmHWM:	   84752 kB
VmRSS:	   82332 kB
RssAnon:	   46476 kB
RssFile:	   35856 kB
RssShmem:	       0 kB
VmData:	 1376432 kB
VmStk:	     132 kB
VmExe:	   48200 kB
VmLib:	    4112 kB
VmPTE:	     536 kB
VmSwap:	       0 kB
Threads:	20
```
i think Resource constraints indeed needs to be considered, but the priority is not the highest .

**Comment by jwzl** [comment]
If it's that,   MetaManger is more like a k8s apiserver.
then,  we can use many kubelet to connect the  MetaManger, and edge node change to a edge cluster.

**Comment by kadisi** [comment]
> If it's that, MetaManger is more like a k8s apiserver.
then, we can use many kubelet to connect the MetaManger, and edge node change to a edge cluster.

@jwzl no, i think `MetaManger` only needs to provide some of the functions of list 、watch and update for kubelet and serve only the kubelet on it`s host.

**Comment by kevin-wangzefeng** [comment]
Thanks for bringing this up. I think the fundamental thing is we need to rethink the relation ship between kubelet and edged.

In the early days implementaion, too many funcionanlities were removed in edged, that's why it took time to add things back into edged when CRI is needed. CSI is another story, since it's not just a plugin framework interacts with Kubelet.

From user perspective, as I said in other places, we need to clairify the feature set that edged offer, and **why some were removed**. Using kubelet in this case is just a lazy way, people today even can't clearly tell what the feature set that kubelet offers.

As I've said many times, we do need to reuse more kubelet code instead of manually forking the implementations.
For the foreseeable future, we can vendor kubelet packages by modules and reconstruct them into edged with only the pecices that are necessary for edge computing. For longer term, we can join upstream to make kubelet more modular.

**Comment by kadisi** [comment]
@kevin-wangzefeng that sounds great, thank you

**Comment by sids-b** [comment]
Agree with @kevin-wangzefeng

As I said earlier, if meta client is implemented in a way that it supports watch like functionality, we will be able to move a lot of code to vendor.
ping @edisonxiang to share his thoughts.

**Comment by sids-b** [comment]
Closing this issue. We can create a new one once we kubelet is more modular and we plan to use it.
