### ISSUE TITLE
controller didn't get renamed to edgecontroller in 05-configmap.yaml

### ISSUE THREAD

**Issue by ryan-esty** [kubeedge/kubeedge#1107]
**What happened**:
When controller got renamed from controller to edgecontroller something got missed

**What you expected to happen**:
Expected to see an edgecontroller section instead of controller

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubeedge/kubeedge/blob/d3cebdf2a12b42ae90a2b2aa37275c853652bc17/build/cloud/05-configmap.yaml#L11
see above link the name controller doesn't match down below in modules it should be edgecontroller now.

Also maybe is it possible to rename line 10 from controller.yaml to controllers.yaml since there is more than one controller now? Not sure if changing the name does anything else in the project.

**Anything else we need to know?**:

**Environment**:
- KubeEdge version:
- Hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Others:

**Comment by fisherxu** [comment]
@ryan-esty Thank you for pointing this out :)
 I renamed the edgecontroller before, and I haven't change it in this config file, because it has many hard code relate to it, like #[config](https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/edgecontroller/config/buffer.go#L59).

And we have a plan do not parse the configuration like this, and unmarshal the yaml file to struct directly. So will change it at that time, thoughts?

@ryan-esty @kadisi @subpathdev

**Comment by kadisi** [comment]
> And we have a plan do not parse the configuration like this, and unmarshal the yaml file to struct directly. So will change it at that time, thoughts?

yes, I recommend not changing the name of the configuration file first .This is not the most urgent thing, and it will bring incompatibility issues. we will solve this problem in the future release.

**Comment by ryan-esty** [comment]
I agree with @kadisi I didn't know if there were things dependent on this name and apparently there is. Solving it in a future release with the least impact is good enough for me.

**Comment by fisherxu** [comment]
@ryan-esty @kadisi Yes agree, let's fix it in a future release :)
