### ISSUE TITLE
Make Verify failing

### ISSUE THREAD

**Issue by sujithsimon22** [kubeedge/kubeedge#125]
**Which jobs are failing**:
verify job has been failing

**Reason for failure**:
gometalinter binary not found

**Comment by sujithsimon22** [comment]
Encountering CI verify fail issue
![image](https://user-images.githubusercontent.com/35599628/51963600-28cb2700-248a-11e9-812b-46367cd31dd1.png)

**Comment by srivatsav123** [comment]
@sujithsimon22 -https://github.com/alecthomas/gometalinter/commits/master/scripts/install.sh
the install script is used by our verify job is getting changed constantly to support windows environment (refer commit history of the script),that's why it is failed since the path where the binaries are generated is getting changed..

**Comment by sids-b** [comment]
> @sujithsimon22 -https://github.com/alecthomas/gometalinter/commits/master/scripts/install.sh
> the install script is used by our verify job is getting changed constantly to support windows environment (refer commit history of the script),that's why it is failed since the path where the binaries are generated is getting changed..

Thanks @srivatsav123 for your support in pointing to the correct issue. Lets have a temporary fix till we move to golangci-lint

**Comment by sujithsimon22** [comment]
@srivatsav123 thanks for your help in identifying the issue. Would be great if you could help us with a fix for it as well...thanks :)

**Comment by srivatsav123** [comment]
@sujit I have raised a PR for the same.. Waiting for it to merge..
