### ISSUE TITLE
Pod has been assigned to edge node and stays pending status

### ISSUE THREAD

**Issue by ghost** [kubeedge/kubeedge#1421]
Environment:
I deployed cloud node on aliyun ECS.   I deployed edge node at home.
Then I added the node to cloud cluster, websocket to communicate.The cluster seems ok:
``` bash
NAME             STATUS   ROLES    AGE   VERSION
kubeedge-master   Ready    master   11h   v1.16.6-beta.0
kubeedge-agent-1       Ready    edge     11h   v1.15.3-kubeedge-v1.1.0
```

I deployed a deployment at the cloud side.  it has been assigned to the edge side,   but it stays pending, and there was no ip  assigned to the pod.  

``` bash
# kubectl get po -n default -o wide
NAME                                READY   STATUS        RESTARTS   AGE   IP       NODE         NOMINATED NODE   READINESS GATES
nginx-deployment-77698bff7d-k4wbg   0/1     Pending   0          10h   <none>   kubeedge-agent-1   <none>           <none>
```

I'm wondering who offering Ip assignment for tyhe pod assigned to the edge node?
and who offering dns resolution for the service runing at edge node, the may be interact with each other.

please help, thanks

**Comment by wuyuting1986** [comment]
The Pod on the edgenode may only support  host network, which means you should  use "hostNetwork: ture" in your Deployment yaml file.   As far as I know, at present, there should be no solution to support cloud and edge POD communication.

**Comment by rahul-1020** [comment]
Hi all, 
  Pod has been assigned to edge node but pods showing status "ContainerCreating " nginx is ruunig because i'm using "  hostNetwork: true ". most of the application not running using hostnetwork. please help how to resolve this issue.


[root@master ~]# kubectl get nodes
NAME      STATUS   ROLES    AGE   VERSION
master    Ready    master   37h   v1.19.0
worker1   Ready    edge     23h   v1.19.3-kubeedge-v1.6.1
worker2   Ready    edge     23h   v1.19.3-kubeedge-v1.6.1

[root@master ~]# kubectl get pods
NAME                                READY   STATUS              RESTARTS   AGE
influxdb                            0/1     ContainerCreating   0          5s
nginx-deployment-77f96fbb65-ktp46   1/1     Running             0          23h
