### ISSUE TITLE
Where is the documentation for deploying the cni plugin?

### ISSUE THREAD

**Issue by liupeidong0620** [kubeedge/kubeedge#1662]
I want to use the k8s cni plugin for networking, what should I do？
Are there any documentation or examples?

**Comment by GsssC** [comment]
1. close edgemesh "modules.edgemesh.enable: false"
2. add a new field "modules.edged.networkPluginName: cni" 
3. confirm all feture used in cnipod.spec.containers are  supported by edgecore.
4. run cni.yaml .

**Comment by mipearlska** [comment]
Sorry for reopening this, I use flannel cni and follow your guide above. However my kube-flannel pod at edge node is still error. I need some help regarding this situation.

Here is the edgecore log related to the kube-flannel pod:
E0612 01:08:08.850230   50290 configmap.go:249] Error creating atomic writer: stat /var/lib/edged/pods/d1d9d77e-0c9c-44ad-8425-b64b20a604d8/volumes/kubernetes.io~configmap/flannel-cfg: no such file or directory
W0612 01:08:08.850299   50290 empty_dir.go:392] Warning: Unmount skipped because path does not exist: /var/lib/edged/pods/d1d9d77e-0c9c-44ad-8425-b64b20a604d8/volumes/kubernetes.io~configmap/flannel-cfg
I0612 01:08:08.850372   50290 record.go:24] Warning FailedMount MountVolume.SetUp failed for volume "flannel-cfg" : stat /var/lib/edged/pods/d1d9d77e-0c9c-44ad-8425-b64b20a604d8/volumes/kubernetes.io~configmap/flannel-cfg: no such file or directory
E0612 01:08:08.850452   50290 nestedpendingoperations.go:270] Operation for "\"kubernetes.io/configmap/d1d9d77e-0c9c-44ad-8425-b64b20a604d8-flannel-cfg\" (\"d1d9d77e-0c9c-44ad-8425-b64b20a604d8\")" failed. No retries permitted until 2020-06-12 01:08:09.35041576 -0700 PDT m=+11.142224414 (durationBeforeRetry 500ms). Error: "MountVolume.SetUp failed for volume \"flannel-cfg\" (UniqueName: \"kubernetes.io/configmap/d1d9d77e-0c9c-44ad-8425-b64b20a604d8-flannel-cfg\") pod \"kube-flannel-ds-amd64-6kpdq\" (UID: \"d1d9d77e-0c9c-44ad-8425-b64b20a604d8\") : stat /var/lib/edged/pods/d1d9d77e-0c9c-44ad-8425-b64b20a604d8/volumes/kubernetes.io~configmap/flannel-cfg: no such file or directory"
E0612 01:08:08.850231   50290 configmap.go:249] Error creating atomic writer: stat /var/lib/edged/pods/f601f210-f98a-4c35-9aa0-00ec8fb1e53b/volumes/kubernetes.io~configmap/kube-proxy: no such file or directory

Here is how kube-system pod status look like:
![image](https://user-images.githubusercontent.com/27221815/84481149-a5058980-acd0-11ea-920d-2d9a699804b4.png)

This is how I edited the edgecore.yaml file:
![image](https://user-images.githubusercontent.com/27221815/84481236-c4041b80-acd0-11ea-9222-80500237b5cc.png)

**Comment by vickiyan** [comment]
Similar issue for me. I use kubeedge version 1.5 with Calico CNI plugin.  The caliconode pod could start successfully on edge node, but Pod deployed to edge node cannot  start successfully with status "Containercreating". 

Is there any document for deploying CNI plugin?

**Comment by GsssC** [comment]
@mipearlska @vickiyan Delpoying cni on edgenode depends on a new kubeedge feature called  `ake`, plz focuz on issue #2760
![image](https://user-images.githubusercontent.com/29768082/115174872-a24ba000-a0fc-11eb-856c-28d406d3e69d.png)

User guide of deploying cni will be released this or next week. 
: )

**Comment by blackdobb** [comment]
> flannel cni and follow your guide above.

hey, have you solve your problem ? i got the same issue

**Comment by linuswagner** [comment]
> 

I assume `cni` refers to the name of the CNI I want to use. Could you be more precise what exactly needs to be filled in? In other words: How does EdgeMesh resolve what I put in the the parameter `modules.edged.networkPluginName`

**Comment by albacanete** [comment]
> > 
> 
> I assume `cni` refers to the name of the CNI I want to use. Could you be more precise what exactly needs to be filled in? In other words: How does EdgeMesh resolve what I put in the parameter `modules.edged.networkPluginName`

Did it work by putting the name of the cni? Or we should literally put "cni"?
