### ISSUE TITLE
Kubeedge‘s message is unreliable. Cloudcore  is no retransmission mechanism 。

### ISSUE THREAD

**Issue by qingcai594** [kubeedge/kubeedge#2015]
Kubeedge‘s message is unreliable. Cloudcore  is no retransmission mechanism 。

If the edge node net status was unstable, i used kubectl create a device, kubectl tell me "device.devices.kubeedge.io/a073003 created"，but the edge node has’t the device.

I0730 10:03:13.392661   29045 process.go:282] DeviceTwin receive msg
I0730 10:03:13.392705   29045 process.go:198] classify the msg with the topic $hw/events/device/a073003/twin/update
I0730 10:03:13.392745   29045 process.go:214] $hw/events/device/ /twin/update
I0730 10:03:13.392774   29045 process.go:224] Classify the msg to action TwinUpdate
I0730 10:03:13.392852   29045 process.go:66] Send msg to the TwinModule module in twin
I0730 10:03:13.392888   29045 twin.go:135] Twin Update EVENT
E0730 10:03:13.392907   29045 dtcontext.go:81] GetMutex device a073003 not exist
I0730 10:03:13.394569   29045 twin.go:161] Begin to update twin of the device a073003
I0730 10:03:13.394686   29045 twin.go:168] Begin to deal device twin of the device a073003
E0730 10:03:13.394717   29045 twin.go:173] Update twin rejected due to the device a073003 is not existed

**Comment by kevin-wangzefeng** [comment]
Thanks for you report, device management is alpha feature and keeps being enhanced during recent releases.
Please feel free to join [SIG Device IOT](https://kubeedge.slack.com/archives/C01239D6PM4) discussions and development to help moving forward.

/cc @fisherxu @luogangyi

**Comment by luogangyi** [comment]
@qingcai594 which version of kubeedge are you using?
And, could you please upload logs of edgecore either?

**Comment by qingcai594** [comment]
I use KubeEdge version 1.3.1。
This problem is easy to reproduce，1.Disconnected the edgecore 2.Used kubectl create a device and then run edgecore  3.Used the example temperature-mapper testing。

**Comment by luogangyi** [comment]
> I use KubeEdge version 1.3.1。
> This problem is easy to reproduce，1.Disconnected the edgecore 2.Used kubectl create a device and then run edgecore 3.Used the example temperature-mapper testing。

It seems current reliable sync mechanism are only working on K8S original resources such as pod, service. Device CRD is not implemented in reliable sync.
We can add this feature in next release.

**Comment by kiteno** [comment]
I am running into the same error with "GetMutex device temperature not exist". Also I noticed the ip addreess on the pod on edge node shows none. Could these two issues potentially be related  network issue? I am running v1.4 and followed set up guide (https://docs.kubeedge.io/en/latest/setup/keadm.html) but it seems to be missing some configuration.
pod/temperature-mapper-8cf4c5c74-2xr8l     1/1     Running   0          20h   <none>         

---------------------
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.346767    3609 process.go:214] $hw/events/device/ /twin/update
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.346785    3609 process.go:224] Classify the msg to action TwinUpdate
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.346797    3609 process.go:66] Send msg to the TwinModule module in twin
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.346822    3609 twin.go:135] Twin Update EVENT
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: E1111 17:35:01.346833    3609 dtcontext.go:81] GetMutex device temperature not exist
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.347984    3609 twin.go:161] Begin to update twin of the device temperature
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: I1111 17:35:01.348002    3609 twin.go:168] Begin to deal device twin of the device temperature
Nov 11 17:35:01 hkthon-edge.ngci.lab.vce.com edgecore[3609]: E1111 17:35:01.348032    3609 twin.go:173] Update twin rejected due to the device temperature is not existed
