### ISSUE TITLE
The data in the edgecore.db database is scattered and incomplete

### ISSUE THREAD

**Issue by qingchen1203** [kubeedge/kubeedge#2150]
**What happened**:
When I use the sqlite3 tool to view the edgecore.db database data, I found that part of the data is scattered and incomplete.
E.g 1：
When getting current edge node information (`type = node`) from the database ， only get “OK”：
`table: meta`   
`key: default/node/k8s-edge`   
`type: node`   
`value: "OK"`
and another field `nodestatus` saves node status information.
The k8s resource object configuration of node cannot be obtained completely, and the `metadata`/`spec` field is missing，and unable to get the k8s resource object configuration of node.
 
There are similar situations in `pod` and `podstatus`: after the values of type=pod are initialized, the pod.status field will not be updated, update only in `podstatus`.

Why do we need so many fields without considering putting them in the same field? For example, all in node and pod.

**Comment by daixiang0** [comment]
I can not reproduce it with latest version(v1.4):
```
sqlite> select * from meta where type="node";
default/node/edge-node|node|{"metadata":{"annotations":{"node.alpha.kubernetes.io/ttl":"0"},"creationTimestamp":"2020-09-04T07:11:18Z","labels":{"kubernetes.io/arch":"amd64","kubernetes.io/hostname":"edge-node","kubernetes.io/os":"linux","node-role.kubernetes.io/agent":"","node-role.kubernetes.io/edge":""},"name":"edge-node","resourceVersion":"592","selfLink":"/api/v1/nodes/edge-node","uid":"48e05129-464f-4c9d-850d-aab73643a35f"},"spec":{"podCIDR":"10.234.1.0/24","podCIDRs":["10.234.1.0/24"]},"status":{"addresses":[{"address":"192.168.1.221","type":"InternalIP"},{"address":"edge-node","type":"Hostname"}],"allocatable":{"cpu":"4","memory":"7875Mi","pods":"110"},"capacity":{"cpu":"2","memory":"7975Mi","pods":"110"},"conditions":[{"lastHeartbeatTime":"2020-09-04T07:11:28Z","lastTransitionTime":"2020-09-04T07:11:28Z","message":"edge is posting ready status","reason":"EdgeReady","status":"True","type":"Ready"}],"daemonEndpoints":{"kubeletEndpoint":{"Port":10350}},"nodeInfo":{"architecture":"amd64","bootID":"","containerRuntimeVersion":"docker://19.3.6","kernelVersion":"4.15.0-91-generic","kubeProxyVersion":"","kubeletVersion":"v1.18.6-kubeedge-v1.4.0","machineID":"","operatingSystem":"linux","osImage":"Ubuntu 18.04.4 LTS","systemUUID":""},"phase":"Running"}}

```

**Comment by qingchen1203** [comment]
Based on commit [update keadm to get latest version from kubeedge.io 2020/8/14 <cc28535a717dc4cac96f406bcd2c5c689cef7e0d> ]   to add my own feature version.

![image](https://user-images.githubusercontent.com/25947812/93418874-e87a2000-f8dd-11ea-8eae-ab6c07af672b.png)

**Comment by GsssC** [comment]
![image](https://user-images.githubusercontent.com/29768082/97165715-16952e80-17bf-11eb-8570-151bdd6f6f4e.png)
Meet this bug too

**Comment by daixiang0** [comment]
@GsssC can reproduce it?

**Comment by GsssC** [comment]
@daixiang0 Sorry for no reproduction way.
/reopen

**Comment by qclc** [comment]
# Analysis of the root cause of bug

## The direct cause of the bug
1. The time for the edgeHub to receive the response message is too short;
2. There is a problem with the logic of the EdgeHub module to determine whether the received message type is response.

## Sequence diagram of bug occurrence
The red step is the direct cause of the bug: 
![2150bugen](https://user-images.githubusercontent.com/39878907/101902484-aff09680-3bed-11eb-8964-5e78b55d2629.png)

### The detailed step for bug occurrence of diagram:
1.Send a Sync type message;

2.1 Set the timer, wait for the response message. It lasts for 15 seconds.

2.2 Create (SyncMsgID, channel) records in the member KeepChannel of EdgeHub

3.Depending on the operation of Sync message, the updateNodeStatus() or updateNode() function in upstream processes the message

4.1 After successful processing, a response message with OK content is returned

4.2 Wait for an ACK message from the edge. It lasts for 25 seconds.

4.3 If edgehub do not receive a response message after the timer arrives(15 seconds), delete the corresponding record in KeepChannel

4.4 Send the response message for the last time

5.The EdgeHub receives the message and determines whether it is a response message based on the Sync
records in the KeepChannel

6.Because the relevant records in KeepChannel were deleted in Step 4.2 as described above, this message is determined to be a regular message to be allocated to MetaManager

7.MetaManager will store this message in SQLlite first, so override the contents of NodeStatus and change it to "OK"

# Proposed solution
Add the code to determine whether the message is a response message according to the value of `msg. Route.Operation ` field.

**Comment by qclc** [comment]
@GsssC Please check the bug analysis.

**Comment by GsssC** [comment]
@threestoneliu PTAL : )

**Comment by threestoneliu** [comment]
@GsssC Why not modify the default value of Heartbeat in the edgehub configuration or add a new configurtion item at the same time ? And I also think the Heartbeat configuration item is not suitable used in this place. https://github.com/kubeedge/kubeedge/blob/master/edge/pkg/edgehub/process.go#L142

**Comment by qclc** [comment]
@threestoneliu I think there is a problem with the time value of waiting for response messages, too. But, considering the time for processing Sync messages in the cloud and the possible network delay, I have not thought of a reasonable time to replace the original value.  
At the same time, the direct cause of this bug is the message judgment error. The judgment logic was modified, so that no matter whether the message was delayed due to other factors, it would not be sent to other modules by mistake, but entered the normal response processing mechanism, so I only modified the message judgment logic without modifying the time value.

**Comment by threestoneliu** [comment]
It look fine to avoid OK stored into sqlite, but will cause `failed to get sync keeper channel,xxxxx` error.

**Comment by qclc** [comment]
@threestoneliu I find a problem with the redundant logic in syncKeeper, and give the problem analysis and optimization recommendations which also can solve the `failed to get sync keeper channel,xxxxx` error. Please take a look and give some suggestions. The link is: https://github.com/kubeedge/kubeedge/pull/2425#issuecomment-753725180
