### ISSUE TITLE
kubeedge can't support deployment Autonomy

### ISSUE THREAD

**Issue by carolove** [kubeedge/kubeedge#2323]
k8s master and cloudcore node: 192.168.1.207
edgecore node: 192.168.1.42
i deploy a deployment at default named nginx-deployment，
1、at first, there is a pod named nginx-deployment-df4cfdd94-rh5xm,   on edge node，status is running
2、edit edgecore.conf, make it wrong, restart edgecore, edgecore disconnected with cloudcore, few mins later,  i found the containers in edge node is right, and in k8s, edge node become unschedule,deployment controller set nginx-deployment-df4cfdd94-rh5xm into Terminating，and recreate a new pod named nginx-deployment-df4cfdd94-flsk7 with pending status
3、make edge reconnected with cloudcore again, edge node clean up all old containers and recreate new containers, deployment controller set nginx-deployment-df4cfdd94-flsk7 into running

i expect deployment controller ignore edge node unschedule status ,and not reschedule po, and when edgenode reconnected into cloudcore, deployment controller  can recovery from old pod, besises, if we can't control deployment controller, i expect edge node don't clean up old containers while still use those containers to adjust deployment controller's reschedle.

**Environment**:
k8s 1.18.8
kubeedge 1.14.0

**Comment by daixiang0** [comment]
In fact what you say more like a feature, please share more details about it: why you need to use it, which case it helps and so on.

Also, you can attend community meeting to talk about it.

/kind-remove bug 
/help

**Comment by SadmiB** [comment]
I strongly agree with you @carolove, I just faced the same problem and came across this issue. because kube edge supports edge autonomy it should recover the state when it gets connected back with the edge rather than creating new deployment.

![image](https://user-images.githubusercontent.com/26244234/103344916-4a772380-4a90-11eb-9944-8de617c8c2fa.png)

@daixiang0 the main reason this is going to be useful is avoiding to disturb production specially if we are running real-time system.

**Comment by Abirdcfly** [comment]
may be same as https://github.com/kubeedge/kubeedge/issues/2385
