### ISSUE TITLE
Is it worth using CloudHub and EdgeHub to implement Cloud/Edge communication?

### ISSUE THREAD

**Issue by drawdy** [kubeedge/kubeedge#2561]
KubeEdge optimized Cloud/Edge communication, decreased the amount of traffic. After reading the source code of CloudCore,
I know that CloudCore maintaines workQueue and cacheStore for resource about Pod, ConfigMap and so on. When capture new resource event,
CloudCore will compare the new resource manifest with the old one in cache, and then discard no updated event.

Below are my questions:

- CloudCore only merge events about Pod, other resource events keep as it is. Comparing the native List-Watch mechanism, how much traffic has been reduced?
- To support the Cloud/Edge communication, CloudCore has to maintain component like SyncController, ReliableSync CRD, LocationCache to implement reliable message
delivery, this futher causes difficulties in CloudCore high availability like leader election mechanism. System complexity increased a lot. Is it worth using the design?

The following is a Chinese translation.

使用 CloudHub 和 EdgeHub 实现云边通信的优势有多大？

KubeEdge 对云边协同通信进行了优化，减少了通信数据量。在阅读了 CloudCore 源码后了解到，
CloudCore 组件在云端维护了一个 workQueue 和 cacheStore 缓存 Pod、ConfigMap 等资源，
在收到新的资源事件时，会先对比缓存中的版本，丢弃没有实质更新的事件。

下面是我的问题：
- 只针对 Pod 进行了重复事件检测，其他资源像 ConfigMap、Secret、Node 等会把所有事件下发，这样相对于原生的 List-Wath 机制能减少多少流量？
- 为了支撑这个云边通信的实现，不得不增加了 SyncController、ReliableSync CRD、LocationCache 等机制保证可靠的消息传输，这进一步导致了 HA CloudCore 需要
选举机制，增加了系统复杂性，这样设计是否值得？

**Comment by fisherxu** [comment]
Great questions!  And thanks for your interest in KubeEdge. @drawdy 

 KubeEdge is designed for edgecomputing, so we must do some enhancements compared to the native mechanism.

> CloudCore only merge events about Pod, other resource events keep as it is.

CloudCore will merge events for all the objects in cloudhub, not only for Pod, you can dig deeper. Ref: https://github.com/kubeedge/kubeedge/blob/master/cloud/pkg/cloudhub/channelq/channelq.go#L115

I think the merge events you mentioned is in podmanager of edgecontroller, it's just the start point.

> Comparing the native List-Watch mechanism, how much traffic has been reduced?

The native List-Watch mechanism is not suitable for scenarios in edgecomputing where the network is unstable, because the client will always do the relist to apiserver when reconnect(will always get all the objects), that's very expensive for edgecomputing.

In kubeedge we add the check mechanism, when client reconnect to the cloud side, we will not send duplicate events. You can ref this issue: https://github.com/k3s-io/k3s/issues/2450

>To support the Cloud/Edge communication, CloudCore has to maintain component like SyncController, ReliableSync CRD, LocationCache to implement reliable message
delivery, this futher causes difficulties in CloudCore high availability like leader election mechanism.

The multi-instances HA is already in our roadmap of Q1, then you can run multiple cloudcore. Ref: https://github.com/kubeedge/kubeedge/issues/2543

**Comment by drawdy** [comment]
@fisherxu Thanks a lot for reply. I will dig deeper.

**Comment by drawdy** [comment]
I tested the relisting effect which indeed consumed a lot of bandwith. Compared with k3s-agent, EdgeCore or EdgeSite had obvious advantage in reconnection.

After reading the source code again, I found some other questions. @fisherxu 

The purpose of MessageQueue is to merge duplicate events/messages. The resourceVersion is the main basis for judging whether it is duplicated. I try to analyze sources of these events:

- Normal controllers like edgeController, DeviceController in CloudCore use List-Watch mechanism, and run in the central cloud with good network. After first listing objects, they only receive new events by watch method. Every new event has a new resourceVersion. MessageQueue has no obvious effect on these events.

- When edgeNode restarts or is offline, SyncController will resend events whose resourceVersion is newer than saved sync objects. This is the main source of duplicated events.

Below are my questions:

- Is the analyzation above right? I doubt the necessary of MessageQueue. Without the MessageQueue, CloudHub sends messages to edge directly when edgeCore is online, otherwise just discards messages. SyncController can resend the unsuccessful messages, to make sure messages are not lost.

- SyncController will list all ojects like Pod, ConfigMap, Secret and so on every five seconds, which increases the load of APIServer. Is it better to replace with first listing and then watching mechanism?
Ref: https://github.com/kubeedge/kubeedge/blob/5849e53a6d6ce1d49bd085f8cffeaf035ca49f88/cloud/pkg/synccontroller/synccontroller.go#L124
