### ISSUE TITLE
Copy the certificate to add the edge node to report an error

### ISSUE THREAD

**Issue by beyondyinjl2** [kubeedge/kubeedge#2791]
kubeedge version: 1.5.0
Due to the validity period of the Token, it may become invalid and cause the failure to add the edge node.

On edge host:
```
mkdir -p /etc/kubeedge
```
On cloud host:
```
cd /etc/kubeedge/
scp -r certs.tgz username@edge_node_ip:/etc/kubeedge
```
On edge host untar the certs.tgz file
```
cd /etc/kubeedge
tar -xvzf certs.tgz
```
On edge host:
```
keadm join --cloudcore-ipport=192.168.3.100:10000 --cgroupdriver=systemd --edgenode-name=edge-node-4 --kubeedge-version=1.5.0
```
 journalctl -u edgecore.service -b
```
Apr 19 02:31:38 edge-node-4 edgecore[9623]: E0419 02:31:38.866774    9623 csi_plugin.go:226] kubernetes.io/csi: CSIDriverLister not found on KubeletVolumeHost
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.867183    9623 fs_resource_analyzer.go:64] Starting FS ResourceAnalyzer
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880830    9623 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880854    9623 log.go:181] DEBUG: ConfigurationFactory Initiated
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880863    9623 log.go:181] INFO: Configuration files: []
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880876    9623 log.go:181] WARN: empty configurtion from [FileSource]
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880881    9623 log.go:181] INFO: invoke dynamic handler:FileSource
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.880903    9623 log.go:181] INFO: archaius init success
Apr 19 02:31:38 edge-node-4 edgecore[9623]: I0419 02:31:38.881380    9623 log.go:181] INFO: create new watcher
Apr 19 02:31:38 edge-node-4 edgecore[9623]: F0419 02:31:38.977749    9623 certmanager.go:91] Error: token credentials are in the wrong format
Apr 19 02:31:38 edge-node-4 edgecore[9623]: goroutine 92 [running]:
Apr 19 02:31:38 edge-node-4 edgecore[9623]: k8s.io/klog.stacks(0xc000a77000, 0xc000626aa0, 0x62, 0x9f)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:883 +0xb9
Apr 19 02:31:38 edge-node-4 edgecore[9623]: k8s.io/klog.(*loggingT).output(0x4b36bc0, 0xc000000003, 0xc0001feb60, 0x482b13a, 0xe, 0x5b, 0x0)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:834 +0x35f
Apr 19 02:31:38 edge-node-4 edgecore[9623]: k8s.io/klog.(*loggingT).printf(0x4b36bc0, 0x3, 0x346c1b6, 0x9, 0xc000b65e10, 0x1, 0x1)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:715 +0x153
Apr 19 02:31:38 edge-node-4 edgecore[9623]: k8s.io/klog.Fatalf(...)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/k8s.io/klog/klog.go:1284
Apr 19 02:31:38 edge-node-4 edgecore[9623]: github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate.(*CertManager).Start(0xc000722a90)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/certificate/certmanager.go:91 +0xd5
Apr 19 02:31:38 edge-node-4 edgecore[9623]: github.com/kubeedge/kubeedge/edge/pkg/edgehub.(*EdgeHub).Start(0xc000722a90)
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/edge/pkg/edgehub/edgehub.go:68 +0x425
Apr 19 02:31:38 edge-node-4 edgecore[9623]: created by github.com/kubeedge/beehive/pkg/core.StartModules
Apr 19 02:31:38 edge-node-4 edgecore[9623]: /root/codes/src/github.com/kubeedge/kubeedge/vendor/github.com/kubeedge/beehive/pkg/core/core.go:23 +0x15a
Apr 19 02:31:39 edge-node-4 systemd[1]: edgecore.service: main process exited, code=exited, status=255/n/a
Apr 19 02:31:39 edge-node-4 systemd[1]: Unit edgecore.service entered failed state.
Apr 19 02:31:39 edge-node-4 systemd[1]: edgecore.service failed.
```

**Comment by sunkai-XDD** [comment]
maybe you can try add --token=xxx , otherwise, you certs can't been checked

**Comment by beyondyinjl2** [comment]
> maybe you can try add --token=xxx , otherwise, you certs can't been checked

Due to the validity period of the Token, the validity period cannot be controlled. After the expiration, it may become invalid and cause the failure of adding the edge node, so I want to use the certificate to add the edge node.
Or is there any way to add edge nodes to prevent the failure of the addition

**Comment by beyondyinjl2** [comment]
To add an edge node, do I have to use a token? How to ensure that the token does not expire when it is added? Is there any other way to add an edge node

**Comment by GsssC** [comment]
@Rachel-Shao PTAL

**Comment by Rachel-Shao** [comment]
According to the source code, when configuring the certificate of edgehub, it will first obtain the certificate according to `edgehub.TLSCertFile` and `edgehub.TLSPrivateKeyFile`. The default values of these two parameters are `/etc/kubeedge/certs/server.crt` and `/etc/kubeedge/certs/server.key` respectively. If they are not obtained (maybe not generated by the cloud), then the certificate application will be implemented through `edgehub.token`.

So I guess that your cloud does not have a corresponding certificate (I remember using `keadm init` does not seem to generate a certificate in `/etc/kubeedge/certs/` by default), and you did not specify a token, so an error was reported.

(If you are interested in the source code, please see [`/kubeedge/edge/pkg/edgehub/certificate/certmanager.go#L87`)](https://github.com/kubeedge/kubeedge/blob/6ea33c760a998c69d51dd3147a79e8ea6b8c5b3b/edge/pkg/edgehub/certificate/certmanager.go#L87)


**solution:**
Use source code to execute `$GOPATH/src/github.com/kubeedge/kubeedge/build/tools/certgen.sh genCertAndKey edge`
(You need to modify your source code path)
Then you will see the generated certificate in `/etc/kubeedge/certs/`, and then execut `keadm join .......`

or

You can use manual deployment instead of `keadm`, by configuring `/etc/kubeedge/config/edgecore.yaml` (fill in the relevant parameters) and start the edgecore binary file, but in the same way, at least one of `server.crt + server.key` and `token` must exist.

The above content comes from my understanding, there may be errors, welcome to discuss.... :)
