### ISSUE TITLE
Add Protocol config for Bluetooth in device_instance_types.go

### ISSUE THREAD

**Issue by sids-b** [kubeedge/kubeedge#379]
**What would you like to be added**:
Protocol config is required for bluetooth device.

**Why is this needed**:
To have protocol specific information to manage the device and add in configmap like MAC, etc

**Comment by sujithsimon22** [comment]
Hi @sids-b, i had previously discussed with @rohitsardesai83 regarding this and we had decided that we do not need to add protocol config for bluetooth. As i understand protocol config contains information specific to the entire protocol as a whole and not specific to any device. Though these were necessary for some protocols (like modbus, which is described in the design), i do not see the need of having such a configuration for bluetooth (since we are only collecting device specific information like device name and the characteristic UUIDs of their required service).

**Comment by sujithsimon22** [comment]
In our current implementation of the bluetooth mapper, I did not see the need of having protocol configs, that is the reason it wasn't added. Would love to hear your take on this, thanks :)
