### ISSUE TITLE
installer : Apply device CRD yamls before installing cloud components

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#452]
**What would you like to be added**:
After doing kubeedge init, Edgecontroller is not starting up, And it has error logs
**Why is this needed**:
Edgecontroller throws error as show in below figure, if the crd yaml is not applied
![devicecrd](https://user-images.githubusercontent.com/39593583/57217620-c2b5e900-7010-11e9-9728-c9fab4e998f4.png)

**Comment by rohitsardesai83** [comment]
@srivatsav123 , see https://github.com/kubeedge/kubeedge/pull/450 , for now we have added a step to do apply the yaml manually. Thanks for covering this in the install flow.

**Comment by sids-b** [comment]
EdgeController will start, deviceController will throw errors as the device api's will not be exposed by apiserver before applying the CRD yamls.

**Comment by srivatsav123** [comment]
@sids-b yes i agree will change the issue title..

**Comment by rohitsardesai83** [comment]
@srivatsav123 , is this taken care of ?

**Comment by srivatsav123** [comment]
currently no...
if we didnt apply these yaml,there will be no effect on the desired output.(kubeedge installer will work fine)
I mean the edge node will sucessfully register , to the edgecontroller...
But since device crds are not created the device controller will not startup and the logs will be shown as put above..

I have a query related to the apply of CRDS should we statically apply the  device yaml(model and instance) from the installer code or we should dynamically allow user to allow/disallow using crds or do modification for the CRD yaml .If he needs some new properties to be added in the crd model or instance??

**Comment by rohitsardesai83** [comment]
we can have an argument to install device crds or not , based on that the yamls need to be applied. The yamls cannot be changed . If new properties need to be added , a PR has to be submitted with code generation.

**Comment by VipinKrizz** [comment]
@sids-b **Error which i am getting while doing keadm init in ubuntu machine version18.04 LS.**
**NOTE**
kubernetes version: 1.14.1
docker version: 18.06.3
kubeedge version: 1.0.0

**ERROR LOG**

al027@k8-master:/usr/local/go/src/github.com/kubeedge/kubeedge/keadm$ sudo ./keadm init --kubeedge-version=1.0.0 --kubernetes-version=1.14.1 --docker-version=18.06.3 --kube-config=/root/.kube/config
Same version of docker already installed in this host
Same version of kubeadm already installed in this hostExpected or Default KubeEdge version 1.0.0 is already downloaded
kubeedge/
kubeedge/edge/
kubeedge/edge/conf/
kubeedge/edge/conf/modules.yaml
kubeedge/edge/conf/logging.yaml
kubeedge/edge/conf/edge.yaml
kubeedge/edge/edge_core
kubeedge/cloud/
kubeedge/cloud/edgecontroller
kubeedge/cloud/conf/
kubeedge/cloud/conf/controller.yaml
kubeedge/cloud/conf/modules.yaml
kubeedge/cloud/conf/logging.yaml
kubeedge/version

+ readonly caPath=/etc/kubeedge/ca
+ caPath=/etc/kubeedge/ca
+ readonly caSubject=/C=CN/ST=Zhejiang/L=Hangzhou/O=KubeEdge/CN=kubeedge.io
+ caSubject=/C=CN/ST=Zhejiang/L=Hangzhou/O=KubeEdge/CN=kubeedge.io
+ readonly certPath=/etc/kubeedge/certs
+ certPath=/etc/kubeedge/certs
+ readonly subject=/C=CN/ST=Zhejiang/L=Hangzhou/O=KubeEdge/CN=kubeedge.io
+ subject=/C=CN/ST=Zhejiang/L=Hangzhou/O=KubeEdge/CN=kubeedge.io
+ genCertAndKey edge
+ ensureFolder
+ '[' '!' -d /etc/kubeedge/ca ']'
+ '[' '!' -d /etc/kubeedge/certs ']'
+ ensureCA
+ '[' '!' -e /etc/kubeedge/ca/rootCA.key ']'
+ '[' '!' -e /etc/kubeedge/ca/rootCA.crt ']'
+ local name=edge
+ openssl genrsa -out /etc/kubeedge/certs/edge.key 2048
Generating RSA private key, 2048 bit long modulus (2 primes)
...........+++++
...........................................+++++
e is 65537 (0x010001)
+ openssl req -new -key /etc/kubeedge/certs/edge.key -subj /C=CN/ST=Zhejiang/L=Hangzhou/O=KubeEdge/CN=kubeedge.io -out /etc/kubeedge/certs/edge.csr
Can't load /home/al027/.rnd into RNG
140399475020224:error:2406F079:random number generator:RAND_load_file:Cannot open file:../crypto/rand/randfile.c:88:Filename=/home/al027/.rnd
+ openssl x509 -req -in /etc/kubeedge/certs/edge.csr -CA /etc/kubeedge/ca/rootCA.crt -CAkey /etc/kubeedge/ca/rootCA.key -CAcreateserial -passin pass:kubeedge.io -out /etc/kubeedge/certs/edge.crt -days 365 -sha256
Signature ok
subject=C = CN, ST = Zhejiang, L = Hangzhou, O = KubeEdge, CN = kubeedge.io
Getting CA Private Key

Certificates got generated at: /etc/kubeedge/ ca and /etc/kubeedge/ certs
certs/
certs/edge.key
certs/edge.csr
certs/edge.crt

Certificates got tared at: /etc/kubeedge/ path, Please copy it to desired edge node (at /etc/kubeedge/ path)
I1204 15:06:04.011078   13037 version.go:240] remote version is much newer: v1.16.3; falling back to: stable-1.14
[init] Using Kubernetes version: v1.14.9
[preflight] Running pre-flight checks
[preflight] Pulling images required for setting up a Kubernetes cluster
[preflight] This might take a minute or two, depending on the speed of your internet connection
[preflight] You can also perform this action in beforehand using 'kubeadm config images pull'
[kubelet-start] Writing kubelet environment file with flags to file "/var/lib/kubelet/kubeadm-flags.env"
[kubelet-start] Writing kubelet configuration to file "/var/lib/kubelet/config.yaml"
[kubelet-start] Activating the kubelet service
[certs] Using certificateDir folder "/etc/kubernetes/pki"
[certs] Generating "ca" certificate and key
[certs] Generating "apiserver" certificate and key
[certs] apiserver serving cert is signed for DNS names [k8-master kubernetes kubernetes.default kubernetes.default.svc kubernetes.default.svc.cluster.local] and IPs [10.96.0.1 192.168.10.24]
[certs] Generating "apiserver-kubelet-client" certificate and key
[certs] Generating "etcd/ca" certificate and key
[certs] Generating "apiserver-etcd-client" certificate and key
[certs] Generating "etcd/server" certificate and key
[certs] etcd/server serving cert is signed for DNS names [k8-master localhost] and IPs [192.168.10.24 127.0.0.1 ::1]
[certs] Generating "etcd/peer" certificate and key
[certs] etcd/peer serving cert is signed for DNS names [k8-master localhost] and IPs [192.168.10.24 127.0.0.1 ::1]
[certs] Generating "etcd/healthcheck-client" certificate and key
[certs] Generating "front-proxy-ca" certificate and key
[certs] Generating "front-proxy-client" certificate and key
[certs] Generating "sa" key and public key
[kubeconfig] Using kubeconfig folder "/etc/kubernetes"
[kubeconfig] Writing "admin.conf" kubeconfig file
[kubeconfig] Writing "kubelet.conf" kubeconfig file
[kubeconfig] Writing "controller-manager.conf" kubeconfig file
[kubeconfig] Writing "scheduler.conf" kubeconfig file
[control-plane] Using manifest folder "/etc/kubernetes/manifests"
[control-plane] Creating static Pod manifest for "kube-apiserver"
[control-plane] Creating static Pod manifest for "kube-controller-manager"
[control-plane] Creating static Pod manifest for "kube-scheduler"
[etcd] Creating static Pod manifest for local etcd in "/etc/kubernetes/manifests"
[wait-control-plane] Waiting for the kubelet to boot up the control plane as static Pods from directory "/etc/kubernetes/manifests". This can take up to 4m0s
[apiclient] All control plane components are healthy after 14.506584 seconds
[upload-config] storing the configuration used in ConfigMap "kubeadm-config" in the "kube-system" Namespace
[kubelet] Creating a ConfigMap "kubelet-config-1.14" in namespace kube-system with the configuration for the kubelets in the cluster
[kubelet-check] Initial timeout of 40s passed.
error execution phase upload-config/kubelet: Error writing Crisocket information for the control-plane node: timed out waiting for the condition
Error: failed to run 'sh -c swapoff -a && kubeadm init --image-repository  "k8s.gcr.io" --pod-network-cidr=100.64.0.0/10' because of error : exit status 1
Usage:
  keadm init [flags]

Examples:

keadm init

- This command will download and install the default version of pre-requisites and KubeEdge

keadm init --kubeedge-version=0.2.1 --kubernetes-version=1.14.1 --docker-version=18.06.3 --kube-config=/root/.kube/config

  - In case, any flag is used in a format like "--docker-version" or "--docker-version=" (without a value)
    then default versions shown in help will be chosen. 
    The versions for "--docker-version", "--kubernetes-version" and "--kubeedge-version" flags should be in the
    format "18.06.3", "1.14.0" and "0.2.1" respectively
  - kube-config is the absolute path of kubeconfig which used to secure connectivity between cloudcore and kube-apiserver


Flags:
      --docker-version string[="18.06.0"]           Use this key to download and use the required Docker version (default "18.06.0")
  -h, --help                                        help for init
      --image-repository string[="k8s.gcr.io"]      Use this key to set the Kubernetes docker image repository (default "k8s.gcr.io")
      --kube-config string                          Use this key to set kube-config path, eg: $HOME/.kube/config
      --kubeedge-version string[="0.3.0"]           Use this key to download and use the required KubeEdge version (default "0.3.0")
      --kubernetes-version string[="1.14.1"]        Use this key to download and use the required Kubernetes version (default "1.14.1")
      --pod-network-cidr string[="100.64.0.0/10"]   Use this key to set the Kubernetes pod Network cidr  (default "100.64.0.0/10")

error: failed to run 'sh -c swapoff -a && kubeadm init --image-repository  "k8s.gcr.io" --pod-network-cidr=100.64.0.0/10' because of error : exit status 1
al027@k8-master:/usr/local/go/src/github.com/kubeedge/kubeedge/keadm$

**Comment by fisherxu** [comment]
Please try latest verion of keadm v1.2.1 :)
/close
