### ISSUE TITLE
Kubeedge Installer to support Centos

### ISSUE THREAD

**Issue by srivatsav123** [kubeedge/kubeedge#454]
**What would you like to be added**:
Kubeedge installer to support centos
**Why is this needed**:
currently the kubeedge installer supports only ubuntu OS.Support to be added for Centos too.
Commands include:
kubedge init  to support Centos
kubeedge reset to support Centos

**Comment by congfairy** [comment]
I have fulfilled the kubeedge installer for centos based on the ubuntu version.I have tested the code and it works. My git is  git@github.com:congfairy/kubeedge.git.I hope it could help .

**Comment by subpathdev** [comment]
@congfairy please create a pull request

**Comment by sids-b** [comment]
@congfairy , it would be great if you could raise a PR :)

**Comment by congfairy** [comment]
Ok,I will do that.



    



    
    
    



    
        
            
                
                    
                        
                    
                    
                        
                            cong
                            
                            
                                
                                    邮箱：congfairy2536@gmail.com
                                
                        
                    
                
            
        
    


Signature is customized by Netease Mail Master


            On 06/14/2019 18:49, Siddharth Bhadri wrote: @congfairy , it would be great if you could raise a PR :)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/kubeedge/kubeedge/issues/454?email_source=notifications\u0026email_token=ADFEFGRY7U5ZXJZ5Y4AZVI3P2NZU7A5CNFSM4HLFNWX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXWODEA#issuecomment-502063504",
"url": "https://github.com/kubeedge/kubeedge/issues/454?email_source=notifications\u0026email_token=ADFEFGRY7U5ZXJZ5Y4AZVI3P2NZU7A5CNFSM4HLFNWX2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODXWODEA#issuecomment-502063504",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by xueyahui1** [comment]
> 我已经完成了基于ubuntu版本的centos的kubeedge安装程序。我已经测试了代码并且可以工作。我的git是 [git@github.com](mailto:git@github.com)：congfairy / kubeedge.git。我希望它能有所帮助。

支持Centos的Kubeedge安装程序能发给我一份吗？非常感谢

**Comment by csehra** [comment]
> 
> 
> I have fulfilled the kubeedge installer for centos based on the ubuntu version.I have tested the code and it works. My git is [git@github.com](mailto:git@github.com):congfairy/kubeedge.git.I hope it could help .

Hi, Cong
I need help installing KubeEdge on my Centos Server, (Kube Cluster is already installed) , Please can you help or share some steps or link to follow. 
Thanks in advance.
Let me know if we can connect on this. 
Reachable on:  chiragsehra44@gmail.com

**Comment by kevin-wangzefeng** [comment]
Closing in favor of https://github.com/kubeedge/kubeedge/issues/454

/close
