### ISSUE TITLE
how to enable device-plugin for special device

### ISSUE THREAD

**Issue by zhangshuo32** [kubeedge/kubeedge#5406]
**failed applying device-plugin**:

**I tried to apply device-plugin for some special accelerator devices with the following yaml (work well on k8s, but fail on kubeedge)**

![image](https://github.com/kubeedge/kubeedge/assets/64187883/68ca7dfc-167d-4494-a889-46fb22ac624a)

**check status on master:**

![image](https://github.com/kubeedge/kubeedge/assets/64187883/728f5f29-50cb-4788-94f3-b2eb25ad8d02)

**log on edge:**
![image](https://github.com/kubeedge/kubeedge/assets/64187883/a550633c-1725-4951-8987-0e93de51ae22)

can anyone give some suggestions to solve it?

**Environment**:
- Kubernetes version 1.26.0
- KubeEdge version 1.15.1
- ubuntu 18.04

**Comment by wbc6080** [comment]
Since there is less error log information, the specific reason may not be clear, but I have a few suggestions that may be helpful. First, you can try to deploy demo nginx pod on kubeedge, as shown in the [document](https://release-1-15.docs.kubeedge.io/docs/setup/install-with-binary/#deploy-demo-on-edge-nodes), to check whether there is a problem with the kubeedge cluster. If nginx can be deployed normally, it means that the kubeedge cluster is running successfully.
Second, if the kubeedge cluster is normal, the problem may be that there is a problem with the application you deployed. Can you check whether the image exists? Or is the mounting path correct? In this part, I recommend that you output the pod logs in detail to observe the reasons for failure.

**Comment by wbc6080** [comment]
By the way, if you want to use kubectl log in kubeedge cluster, please follow the [documentation](https://release-1-15.docs.kubeedge.io/docs/setup/install-with-keadm#enable-kubectl-logs-feature)

**Comment by zhangshuo32** [comment]
application error, already solved, thanks!
