### ISSUE TITLE
execute keadm command failed

### ISSUE THREAD

**Issue by SherlockShemol** [kubeedge/kubeedge#5434]
**What happened and what you expected to happen**:
previously I use minikube to start a cluster,I [failed to get CA certificate](https://github.com/kubeedge/kubeedge/issues/5433) so I change minikube to kubeadm.
after I run `sudo keadm init --kube-config=/home/shemol/.kube/config --advertise-address=127.0.0.1 --profile version=v1.15.1` I got 
```
execute keadm command failed:  Get "https://192.168.199.232:6443/apis/apps/v1/namespaces/kubeedge/daemonsets/edge-eclipse-mosquitto": dial tcp 192.168.199.232:6443: connect: connection refused
```
I have no idea how to fix that.Does this have something to do with the [new features of keadm v1.16.0](https://mp.weixin.qq.com/s/P0pG8FoMgZsNcbVargK2gg)? 
> 新版本我们使用 DaemonSet 来管理边端的 MQTT 服务 Eclipse Mosquitto

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Kubernetes version (use `kubectl version`):
```
Client Version: v1.29.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.2
```
- KubeEdge version(e.g. `cloudcore --version` and `edgecore --version`):

**Comment by wbc6080** [comment]
If you are upgrading an old edge node, you can refer to the steps proposed in this [issue](https://github.com/kubeedge/kubeedge/issues/5233) to complete compatibility with the old version.
If not, you may be able to execute the command `kubectl get all -n kubeedge`  like [page](https://github.com/kubeedge/kubeedge/pull/5235) to view the status of the edge-eclipse-mosquitto pod in the kubernetes cluster to see whether the creation failed due to image problem or other reasons.
