### ISSUE TITLE
Observations and suggestions on issue management in the KubeEdge Project

### ISSUE THREAD

**Issue by magichan** [kubeedge/kubeedge#5838]
As someone who hasn't deeply engaged in the KubeEdge project yet, I rely on the status of issues to determine whether I can address them. However, I've noticed that the status settings for some issues are not standardized, which occasionally confuses me.

For example:

In this [issue](https://www.github.com/kubeedge/kubeedge/issues/5561) , there was no actual assignment until it was closed.
In this [issue](https://www.github.com/kubeedge/kubeedge/issues/5595), the proposal wasn't merged, but the MR (Merge Request) was already submitted.
In this [issue](https://www.github.com/kubeedge/kubeedge/issues/5604), it's a question, not a feature.
In this [issue](https://www.github.com/kubeedge/kubeedge/issues/5593), it was raised in July, but there was no progress in August.

As a result, I'm unable to determine which issues are unassigned and which ones had someone responsible but have had no feedback for a long time, making them candidates for reassignment.

Therefore, I suggest that if you come across an issue that is not properly standardized, please take a moment to comment and update it.

By the way, when is the deadline for v1.19?

**Comment by magichan** [comment]
i will close the issue after commuity meeting.

**Comment by magichan** [comment]
> /remove-label kind/question

this is for testing prow, please ignore it.

**Comment by Shelley-BaoYue** [comment]
#5561 is a LFX project, so assignment is made on LFX official website. But indeed it should also assign developer in issue. 

https://github.com/kubeedge/kubeedge/issues/5595 proposal has been reviewed and passed on community meeting.

https://github.com/kubeedge/kubeedge/issues/5604  Although community has already defined some categories for issues, there are some users who are not familiar with open source, so there may be some issues which lable is not suitable. I think it's quite normal, you can reminder them to modify the label : )

https://github.com/kubeedge/kubeedge/issues/5593 is a OSPP project. The deadline of OSPP is at the end of October, so it's normal that there's no progress at present. 

https://kubeedge.io/docs/community/release   KubeEdge releases currently happen approximately every three months. So that 1.19 will be released at the end of October. You can also ref to 1.19 milestone to get the progress of this release.

**Comment by magichan** [comment]
After promoting the issue within the community, close it.
