### ISSUE TITLE
split ci in different stages

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#810]
**What would you like to be added**:
It could be useful to split the CI in different stages.
- build all parts
- unit tests
- e2e test
- cross build
....

**Why is this needed**:
- increase clearity of the ci tests

toughs?

**Comment by rohitsardesai83** [comment]
:+1: , can we have some proposal / design on how to do this ?

**Comment by subpathdev** [comment]
@rohitsardesai83 I will create it.

**Comment by sids-b** [comment]
@subpathdev , all stages are executed serially. So it increases the time required for CI to pass for a PR. Since our e2e and UT's take a lot of time to pass, we currently have only 2 stages
1) dep check
2) All other checks
Lets carefully think of the order of stages as well as jobs in a stage so as to reduce the time in CI. (for eg: e2e and UT in same stage).

**Comment by kevin-wangzefeng** [comment]
@sids-b 
2 stages is not enough.
For example UT can run in parallel with e2e tests, and we need to make it visibable which test job failed in the status section under a Pull Request.

A fine grained PR checking setup makes it easier to enable more prow functionalities including skiping those already succeeded when executing `retest` command.

**Comment by subpathdev** [comment]
I think it would be useful to have the following stages:
1. test build -> if this failed no other stages has to be executed
2. test lint
3. test ut + e2e
4. test build docker images

I like splitting ut and e2e but I think this would increase the time in the ci.  I removed the dep check  stage because I think we start using gomod. (If not this would be on stage 0)
@kevin-wangzefeng what are you thinking about this stages?

**Comment by kevin-wangzefeng** [comment]
Generally sounds good to me.

But I think splitting UT and e2e should actually reduce the CI time.
Probably some configurations need to be improved as well.


Jan Unterbrink <notifications@github.com> 于 2019年7月23日周二 03:20写道：

**Comment by rohitsardesai83** [comment]
:+1:  to the ideas.
To add, we also need to optimize / refactor our e2e tests so that we avoid running tests like repeated creation / deletion of pods . We are not testing performance in our e2e tests , but we are testing whether the e2e flow works fine. So we can remove tests which do much more than check e2e sanity and reduce the CI time.

**Comment by subpathdev** [comment]
I will split the travis in the mentioned parts.
/assign subpathdev

**Comment by subpathdev** [comment]
lets have the discussion about e2e here: #951
