### ISSUE TITLE
prometheus exporter on the cloud component

### ISSUE THREAD

**Issue by subpathdev** [kubeedge/kubeedge#907]
**What would you like to be added**:
a prometheus exporter of the reported and expected device values
(supported value types are: int, float and bool ( true = 1; false = 0 ))

**Why is this needed**:
users can monitor theire devices and we have a way to display values without using kubernetes specif commands (like kuebctl get device ....).
When they installing prometheus they could also view the history of device values.

Thoughts?

**Comment by rohitsardesai83** [comment]
We need monitoring solutions like prometheus to get useful data like you suggested.
we can monitor all edge nodes running , their status , number of devices , their desired / reported states etc.
Also, we need to think about efficient ways of monitoring at the edge as well, since in offline scenarios, monitoring at the edge would become important. 
We need to start thinking of best approaches for such monitoring requirements like less footprint , resource usage at the edge.
