### ISSUE TITLE
Edgemesh Test Failture

### ISSUE THREAD

**Issue by liyongxian** [kubeedge/kubeedge#961]
Hi @sids-b 
When I Test Edgemesh,Meet something wrong. According to **https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md**
**The status of Server Pod is ContainerCreating.** 
![1111](https://user-images.githubusercontent.com/18571576/61860471-98334800-aefc-11e9-8853-fdb1c445c5d4.jpg)

**Error Info:**
![222222](https://user-images.githubusercontent.com/18571576/61859961-b8aed280-aefb-11e9-819b-ca24170b5f90.jpg)

**Why "Make sure docker0 does not exist"** .
![33333](https://user-images.githubusercontent.com/18571576/61860604-d29ce500-aefc-11e9-812d-75c7ee6411e6.jpg)

If different edge nodes need to defferent subnet of docker0,can modify the subnet by command.
Please tell me Why.
Thanks.

**Comment by liyongxian** [comment]
@sids-b  Please. Thanks.

**Comment by sids-b** [comment]
cc @arcanique @anyushun ... can you please take a look at this one ??

**Comment by arcanique** [comment]
@liyongxian  

> Hi @sids-b
> When I Test Edgemesh,Meet something wrong. According to **https://github.com/kubeedge/kubeedge/blob/master/docs/guides/edgemesh_test_env_guide.md**
> **The status of Server Pod is ContainerCreating.**
> ![1111](https://user-images.githubusercontent.com/18571576/61860471-98334800-aefc-11e9-8853-fdb1c445c5d4.jpg)
> 
> **Error Info:**
> ![222222](https://user-images.githubusercontent.com/18571576/61859961-b8aed280-aefb-11e9-819b-ca24170b5f90.jpg)
> 
> **Why "Make sure docker0 does not exist"** .
> ![33333](https://user-images.githubusercontent.com/18571576/61860604-d29ce500-aefc-11e9-812d-75c7ee6411e6.jpg)
> 
> If different edge nodes need to defferent subnet of docker0,can modify the subnet by command.
> Please tell me Why.
> Thanks.

@liyongxian In the first question, the dns policy will fall back to the default because the clusterDNS in the edge.yaml configuration file is not configured. This issue will not affect the application deployment. Just the DNS name server on the host's DNS name server integration host in the pod. And "Why "Make sure docker0 does not exist" ", There are two points for this problem. Use docker0 to be compatible with both container and containerd container drivers. And if  choose containerd, make sure that docker0 does not exist, mainly to prevent the network segment configured in "10-mynet.conf " from conflicting with the default network segment on docker0.

**Comment by arcanique** [comment]
@liyongxian Can you provide me with your edge.yaml file?

**Comment by sids-b** [comment]
@liyongxian , are you still facing this issue ?

**Comment by sids-b** [comment]
Closing this issue. Please reopen or reach out to us via slack for further discussions.
