### ISSUE TITLE
Survey: How can we support edge application development?

### ISSUE THREAD

**Issue by qizha** [kubeedge/kubeedge#991]
I am creating this issue to continue the discussion in slack about what is the edge application looks like and what is the different between cloud application. Actually, the purpose of that is to think about what can we do to support the edge application development. Maybe a code generation tool like swagger code-gen? 
Well, for the disscussion in slack, there are some points for the edge applications:
1. Event-driven instead of the REST service
2. Monolithic instead of microservice architecture 

Just like Ray said:
_I think edge application has much different with cloud application, cloud application always provide some services to user or business application，but edge application always provide services to some job script or tasks. my edge application just like a scheduler，it subscribe data by mqtt，when  i get the value, it can trigger a task which been defined, and this task will send result to cloud by self. so this edge application has no GUI and RESTful interface, and it don't need been control when it is running._

So, what do you think for this topic? Please leave your comments in this issue.

**Comment by hw2018** [comment]
I think edge applications should be event-driven.Edge computing should be a complement to cloud computing power, the ability to respond quickly to the last mile, rather than replacing some of the capabilities of cloud computing. But how does serverless develop in the edge ? On the cloud, faas baas is a good friend, we can quickly build own serverless application through faas and baas, but on the edge side, there is only faas, we can do very little.Faas is a glue that can only grow rapidly when it can connect to more services. At the edge, if faas can connect more services, and we can use it like on cloud ,  then I think based on Event-driven edge applications can also develop rapidly.
